// Generated by gencpp from file robotic_armv5/Floats_array.msg
// DO NOT EDIT!


#ifndef ROBOTIC_ARMV5_MESSAGE_FLOATS_ARRAY_H
#define ROBOTIC_ARMV5_MESSAGE_FLOATS_ARRAY_H

#include <ros/service_traits.h>


#include <robotic_armv5/Floats_arrayRequest.h>
#include <robotic_armv5/Floats_arrayResponse.h>


namespace robotic_armv5
{

struct Floats_array
{

typedef Floats_arrayRequest Request;
typedef Floats_arrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Floats_array
} // namespace robotic_armv5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotic_armv5::Floats_array > {
  static const char* value()
  {
    return "086e0a6631d243c06d9ccfa024bfe376";
  }

  static const char* value(const ::robotic_armv5::Floats_array&) { return value(); }
};

template<>
struct DataType< ::robotic_armv5::Floats_array > {
  static const char* value()
  {
    return "robotic_armv5/Floats_array";
  }

  static const char* value(const ::robotic_armv5::Floats_array&) { return value(); }
};


// service_traits::MD5Sum< ::robotic_armv5::Floats_arrayRequest> should match
// service_traits::MD5Sum< ::robotic_armv5::Floats_array >
template<>
struct MD5Sum< ::robotic_armv5::Floats_arrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotic_armv5::Floats_array >::value();
  }
  static const char* value(const ::robotic_armv5::Floats_arrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotic_armv5::Floats_arrayRequest> should match
// service_traits::DataType< ::robotic_armv5::Floats_array >
template<>
struct DataType< ::robotic_armv5::Floats_arrayRequest>
{
  static const char* value()
  {
    return DataType< ::robotic_armv5::Floats_array >::value();
  }
  static const char* value(const ::robotic_armv5::Floats_arrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotic_armv5::Floats_arrayResponse> should match
// service_traits::MD5Sum< ::robotic_armv5::Floats_array >
template<>
struct MD5Sum< ::robotic_armv5::Floats_arrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotic_armv5::Floats_array >::value();
  }
  static const char* value(const ::robotic_armv5::Floats_arrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotic_armv5::Floats_arrayResponse> should match
// service_traits::DataType< ::robotic_armv5::Floats_array >
template<>
struct DataType< ::robotic_armv5::Floats_arrayResponse>
{
  static const char* value()
  {
    return DataType< ::robotic_armv5::Floats_array >::value();
  }
  static const char* value(const ::robotic_armv5::Floats_arrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIC_ARMV5_MESSAGE_FLOATS_ARRAY_H
